version: "3.7"
services:
  web:
    build:
      context: .
      target: dev
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    command: ./bin/start_dev_server
    volumes:
      - ".:/rugb-rag"
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "ankane/pgvector"
    environment:
      POSTGRES_PASSWORD: db_password
    volumes:
      - api-data:/var/lib/postgresql/data
volumes:
  bundle:
  api-data:
